apiVersion: v1
kind: Service
metadata:
  name: hermes-service
  namespace: hermes
spec:
  type: NodePort
  selector:
    app: hermes-webui
  ports:
    - port: 80
      targetPort: 8643
      nodePort: 30081
