services:
  loki:
    container_name: loki
    image: grafana/loki:latest
    ports:
      - "3100:3100"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml

  alloy:
    container_name: alloy
    image: grafana/alloy:latest
    ports:
      - "12345:12345"
    volumes:
      - ./alloy:/etc/alloy/
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_LOG_LEVEL=debug
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
