#cloud-config
timezone: "UTC"

users:
  - name: "ubuntu"
    lock_passwd: true
    groups:
      - sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key}
    sudo: ALL=(ALL) NOPASSWD:ALL
  - name: root
    lock_passwd: true
    ssh_authorized_keys: []

package_update: true
package_upgrade: true

packages:
  - qemu-guest-agent
  - curl

write_files:
  - path: /etc/rancher/k3s/config.yaml
    content: |
      token: ${k3s_token}
      write-kubeconfig-mode: "0644"
      tls-san: ["${ip}"]
      cluster-init: true
    owner: root:root
    permissions: "0600"

swap:
  filename: /swap.img
  size: 0
  maxsize: 0

runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - swapoff -a
  - curl -sfL https://get.k3s.io | sh -s - server
  - echo "done" > /tmp/cloud-config.done
