apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-config
  namespace: forgejo
data:
  FORGEJO_HOST: "forgejo.cluster.local"
  FORGEJO_PORT: "3000"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "forgejo"
