#cloud-config
timezone: "UTC"
hostname: ${hostname}

users:
  - default
  - name: "user"
    lock_passwd: true
    groups:
      - sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key}
    sudo: ALL=(ALL) NOPASSWD:ALL
  - name: root
    lock_passwd: true
    ssh_authorized_keys: []

package_update: true
package_upgrade: true

packages:
  - qemu-guest-agent
  - curl

swap:
  filename: /swap.img
  size: 0
  maxsize: 0

runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - swapoff -a
  - curl -sfL https://get.k3s.io | K3S_TOKEN=${token} sh -s - --cluster-init --write-kubeconfig-mode=644
  - echo "done" > /tmp/cloud-config.done
